#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("WritePadXamarinSample.Resource", IsApplication=true)]

namespace WritePadXamarinSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int ClearButton = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int LanguageButton = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int OptionsButton = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int RecognizeButton = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int autocorrector = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int autolearner = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int dict_words = 2131034125;
			
			// aapt resource value: 0x7f050002
			public const int ink_view = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int ready_text = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int ready_text_title = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int separate_letters = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int single_word = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int user_dictionary = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Options = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000b
			public const int ApplicationName = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int Autocorrector = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int Clear = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int DictWordsOnly = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int Language = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int Learner = 2130968584;
			
			// aapt resource value: 0x7f040003
			public const int Options = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Recognize = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int SeparateLetters = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int SingleWord = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int Title = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int UserDictionary = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
