#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WritePadXamarinSample.Resource", IsApplication=true)]

namespace WritePadXamarinSample
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020004
			public const int autocorrector = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int autolearner = 2130837509;
			
			// aapt resource value: 0x7F020000
			public const int ClearButton = 2130837504;
			
			// aapt resource value: 0x7F020006
			public const int dict_words = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int ink_view = 2130837511;
			
			// aapt resource value: 0x7F020001
			public const int LanguageButton = 2130837505;
			
			// aapt resource value: 0x7F020008
			public const int linearLayout1 = 2130837512;
			
			// aapt resource value: 0x7F020002
			public const int OptionsButton = 2130837506;
			
			// aapt resource value: 0x7F020009
			public const int ready_text = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int ready_text_title = 2130837514;
			
			// aapt resource value: 0x7F020003
			public const int RecognizeButton = 2130837507;
			
			// aapt resource value: 0x7F02000B
			public const int separate_letters = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int single_word = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int user_dictionary = 2130837517;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Options = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Autocorrector = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int Clear = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int DictWordsOnly = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int Language = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int Learner = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int Options = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int Recognize = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int SeparateLetters = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int SingleWord = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int Title = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int UserDictionary = 2130968587;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
